dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3

compiler:
  solc:
    version: 0.8.0

networks:
  default: development
  development:
    gas_limit: 6721975
    gas_price: 0
    revert: true
